version: '3.8'

services:
  web:
    build: .
    container_name: flask_app
    restart: always
    depends_on:
      - db
    environment:
      - FLASK_ENV=production
    expose:
      - 5000
    networks:
      - backend

  db:
    image: mariadb
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: task_manager
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
    depends_on:
      - web
    networks:
      - backend

volumes:
  db_data:

networks:
  backend:
